name: fuzzy_greenhouse
description: Mobile app for control and monitoring of the Fuzzy Greenhouse.

publish_to: 'none'

version: 0.2.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #---NETWORK DATA---#
  firebase_core: 4.2.1
  firebase_auth: 6.1.1
  firebase_database: 12.0.3
  firebase_messaging: 16.0.4
  cloud_firestore: 6.1.0
  googleapis_auth: 2.0.0

  http: 1.6.0

  #---STATE MANAGEMENT---#
  flutter_bloc: 9.1.1

  #---UI---#
  flutter_svg: 2.2.1
  cupertino_icons: 1.0.8

  #---MODEL---#
  json_annotation: 4.9.0
  equatable: 2.0.7

  flutter_map: 8.2.2
  flutter_local_notifications: 19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  #---GENERATOR---#
  build_runner: 2.7.1
  json_serializable: 6.11.1
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  path: ../

flutter_icons:
  image_path_ios: 'assets/images/app_logo.webp'
  image_path_android: 'assets/images/app_logo.webp'
  adaptive_icon_background: 'assets/images/app_logo.webp'
  adaptive_icon_foreground: 'assets/images/app_logo.webp'
  android: true
  ios: true